version: '3'
services:
  nginx:
    build:
      dockerfile: ./docker/nginx.dockerfile
      context: .
    image: midia/nginx
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - production-network
    depends_on:
      - "node"
  node:
    build:
      dockerfile: ./docker/angular.dockerfile
      context: .
    image: midia/cdnjs
    container_name: cdnjs
    ports:
      - "3000"
    networks:
      - production-network
networks:
  production-network:
    driver: bridge
